# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.label_2.setObjectName("label_2")
        self.chance_image = QtWidgets.QToolButton(self.centralwidget)
        self.chance_image.setGeometry(QtCore.QRect(450, 30, 31, 31))
        self.chance_image.setObjectName("chance_image")
        self.chance_template = QtWidgets.QToolButton(self.centralwidget)
        self.chance_template.setGeometry(QtCore.QRect(450, 80, 31, 31))
        self.chance_template.setObjectName("chance_template")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 190, 141, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 240, 131, 31))
        self.label_6.setObjectName("label_6")
        self.start_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.start_analysis.setGeometry(QtCore.QRect(180, 370, 131, 51))
        self.start_analysis.setObjectName("start_analysis")
        self.min_threshold = QtWidgets.QTextEdit(self.centralwidget)
        self.min_threshold.setGeometry(QtCore.QRect(140, 190, 81, 31))
        self.min_threshold.setObjectName("min_threshold")
        self.max_threshold = QtWidgets.QTextEdit(self.centralwidget)
        self.max_threshold.setGeometry(QtCore.QRect(140, 240, 81, 31))
        self.max_threshold.setObjectName("max_threshold")
        self.min_bin_threshold = QtWidgets.QTextEdit(self.centralwidget)
        self.min_bin_threshold.setGeometry(QtCore.QRect(400, 190, 81, 31))
        self.min_bin_threshold.setObjectName("min_bin_threshold")
        self.max_bin_threshold = QtWidgets.QTextEdit(self.centralwidget)
        self.max_bin_threshold.setGeometry(QtCore.QRect(400, 240, 81, 31))
        self.max_bin_threshold.setObjectName("max_bin_threshold")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 141, 31))
        self.label_7.setObjectName("label_7")
        self.chance_analysis = QtWidgets.QToolButton(self.centralwidget)
        self.chance_analysis.setGeometry(QtCore.QRect(450, 130, 31, 31))
        self.chance_analysis.setObjectName("chance_analysis")
        self.image_path = QtWidgets.QLineEdit(self.centralwidget)
        self.image_path.setGeometry(QtCore.QRect(140, 30, 311, 31))
        self.image_path.setObjectName("image_path")
        self.template_path = QtWidgets.QLineEdit(self.centralwidget)
        self.template_path.setGeometry(QtCore.QRect(140, 80, 311, 31))
        self.template_path.setObjectName("template_path")
        self.analysis_path = QtWidgets.QLineEdit(self.centralwidget)
        self.analysis_path.setGeometry(QtCore.QRect(140, 130, 311, 31))
        self.analysis_path.setObjectName("analysis_path")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 322, 471, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label.raise_()
        self.label_2.raise_()
        self.chance_template.raise_()
        self.chance_image.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.start_analysis.raise_()
        self.min_threshold.raise_()
        self.max_threshold.raise_()
        self.min_bin_threshold.raise_()
        self.max_bin_threshold.raise_()
        self.label_7.raise_()
        self.chance_analysis.raise_()
        self.image_path.raise_()
        self.template_path.raise_()
        self.analysis_path.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 22))
        self.menubar.setObjectName("menubar")
        self.menuopen_img_file = QtWidgets.QMenu(self.menubar)
        self.menuopen_img_file.setObjectName("menuopen_img_file")
        MainWindow.setMenuBar(self.menubar)
        self.chance_image_file = QtWidgets.QAction(MainWindow)
        self.chance_image_file.setObjectName("chance_image_file")
        self.chance_template_file = QtWidgets.QAction(MainWindow)
        self.chance_template_file.setObjectName("chance_template_file")
        self.menubar.addAction(self.menuopen_img_file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "image file path:"))
        self.label_2.setText(_translate("MainWindow", " template path:"))
        self.chance_image.setText(_translate("MainWindow", "..."))
        self.chance_template.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "min threshold:"))
        self.label_4.setText(_translate("MainWindow", "max threshold:"))
        self.label_5.setText(_translate("MainWindow", "min bin threshold:"))
        self.label_6.setText(_translate("MainWindow", "max bin threshold:"))
        self.start_analysis.setText(_translate("MainWindow", "start analysis"))
        self.label_7.setText(_translate("MainWindow", "analysisi save path:"))
        self.chance_analysis.setText(_translate("MainWindow", "..."))
        self.menuopen_img_file.setTitle(_translate("MainWindow", "file"))
        self.chance_image_file.setText(_translate("MainWindow", "image_file"))
        self.chance_template_file.setText(_translate("MainWindow", "template_file"))

